### ISSUE TITLE
Preview shows distorted and captured photos are not in high resolution

### ISSUE THREAD

**Issue by dharmendrainnovify** [arindamxd/android-camerax#3]
I want to achieve two things
1. Camera preview should be always focused on. The camera should not try to autofocus it should be a continuous focus. Like we can use focus mode to be Camera.Parameters.FOCUS_MODE_CONTINUOUS_PICTURE in Camera API.
2. When I take photo, it is not saving in maximum resolution even though, I have set setCaptureMode(CaptureMode.MAX_QUALITY) in the ImageCapture config.

**Comment by arindamxd** [comment]
@dharmendrainnovify Can you please let me know that this issue is fixed or not?
